import random
from lxml import etree

def create_mock_nessus_file(filename="mock_scan.nessus", num_hosts=500, items_per_host=100):
    CM_URI = "http://www.nessus.org/cm"
    NSMAP = {"cm": CM_URI}
    
    TARGET_IDS = ["20811", "22869", "83991", "45590", "19506"]

    root = etree.Element("NessusClientData_v2", nsmap=NSMAP)
    policy = etree.SubElement(root, "Policy")
    etree.SubElement(policy, "policyName").text = "Mock Audit Policy"
    
    report = etree.SubElement(root, "Report", name="Mock Scan Job")

    risks = ["None", "Low", "Medium", "High", "Critical"]
    families = ["Windows", "CGI Abuses", "General", "Compliance"]

    count = 0

    for i in range(num_hosts):
        host_ip = f"192.168.1.{10 + i}"
        host = etree.SubElement(report, "ReportHost", name=host_ip)
        
        props = etree.SubElement(host, "HostProperties")
        tags = {
            "host-ip": host_ip,
            "operating-system": "Windows Server 2019" if i % 2 == 0 else "Linux Kernel 5.4",
            "mac-address": f"00:11:22:33:44:5{i % 10}",
            "HOST_START": "Mon Jan 01 10:00:00 2024",
            "HOST_END": "Mon Jan 01 10:30:00 2024",
            "Credentialed_Scan": "true"
        }
        for k, v in tags.items():
            tag = etree.SubElement(props, "tag", name=k)
            tag.text = v

        for j in range(items_per_host):
            severity = random.randint(0, 4)
            
            if j % 20 == 0:
                p_id = random.choice(TARGET_IDS)
                p_name = f"Targeted Plugin {p_id} (Regex Test)"
            else:
                p_id = str(10000 + j)
                p_name = f"Mock Vulnerability {j}"

            item = etree.SubElement(host, "ReportItem", 
                port="443", 
                svc_name="https", 
                protocol="tcp",
                severity=str(severity),
                pluginID=p_id,
                pluginName=p_name,
                pluginFamily=random.choice(families)
            )

            etree.SubElement(item, "description").text = "This is a mock description."
            etree.SubElement(item, "risk_factor").text = risks[severity]
            etree.SubElement(item, "solution").text = "Patch the system."
            
            for _ in range(random.randint(0, 2)):
                etree.SubElement(item, "cve").text = f"CVE-2023-{random.randint(1000,9999)}"
            
            if j % 3 == 0:
                etree.SubElement(item, "cpe").text = "cpe:/o:microsoft:windows_server_2019"

            if p_id in TARGET_IDS:
                hidden_cve = f"CVE-2025-{random.randint(1000,9999)}"
                hidden_cpe = "cpe:/a:apache:http_server:2.4.50"
                
                output_text = (
                    f"Output generated by plugin {p_id}.\n"
                    f"Remote version: 1.0\n"
                    f"Vulnerability detected: {hidden_cve}\n"
                    f"Platform: {hidden_cpe}\n"
                    "End of check."
                )
                etree.SubElement(item, "plugin_output").text = output_text

            if severity > 0:
                etree.SubElement(item, "cvss_base_score").text = str(random.uniform(4.0, 10.0))[:3]
                etree.SubElement(item, "cvss_vector").text = "AV:N/AC:L/Au:N/C:P/I:P/A:P"

            if j % 10 == 0:
                etree.SubElement(item, "compliance").text = "true"
                etree.SubElement(item, f"{{{CM_URI}}}compliance-check-name").text = "Check SSH Configuration"
                etree.SubElement(item, f"{{{CM_URI}}}compliance-result").text = "FAILED"
                etree.SubElement(item, f"{{{CM_URI}}}compliance-actual-value").text = "PermitRootLogin yes"
                etree.SubElement(item, f"{{{CM_URI}}}compliance-audit-file").text = "CIS_CentOS_7.audit"
            
            count += 1

    tree = etree.ElementTree(root)
    tree.write(filename, pretty_print=True, xml_declaration=True, encoding="UTF-8")
    print(f"Successfully generated {filename}")
    print(f"Stats: {num_hosts} Hosts, {count} Items total.")
    print(f"Injected Target IDs ({', '.join(TARGET_IDS)}) with raw regex-able data.")

if __name__ == "__main__":
    create_mock_nessus_file()